# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 361425b42a8fb815a907e86a727aa5f7c845a529e3b596cae87626b473cbf5e077abfc60169f20971db3c246679ca5e535272bb5a2f180f36bac7172946a7f64

test:
  secret_key_base: 547dbe7578ee1fe13369ba14eb8223cf49ba65e3cd5ee210d70ea59d0226e3973dccf8377161ade61c946026a59e5206af452a93fc54aca61dba27102cbf8758

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
